# Generated by Django 4.0.3 on 2023-02-08 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_answer_modify_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='modify_date',
            new_name='answer_modify_date',
        ),
    ]
