# Generated by Django 4.0.3 on 2023-02-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_rename_modify_date_answer_answer_modify_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_modify_date',
        ),
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
