# Generated by Django 4.0.3 on 2023-02-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_answer_modify_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='modify_date',
        ),
    ]
